---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: licenses, licensing, subscriptions, annual subscription, paygo, hourly subscription 
summary: 14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは、 AWS または Azure から従量課金制または年払いのいずれかを購読することです。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。 
---
= ライセンスの概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは、 AWS または Azure から従量課金制または年払いのいずれかを購読することです。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。



== Marketplace サブスクリプション

AWS または Azure から Cloud Sync サービスに加入すると、 1 時間あたりの料金を支払うか、年間の料金を支払うことができます。 link:task-licensing.html["AWS または Azure でサブスクライブできます"]、どこに課金するかによって異なります。



=== 時間単位のサブスクリプション

時間単位の従量課金制サブスクリプションでは、作成した同期関係の数に基づいて 1 時間ごとに課金されます。

* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure で価格を表示します"^]
* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS で従量課金制の価格を確認できます"^]




=== 年間サブスクリプション

年間サブスクリプションでは、事前に支払う 20 の同期関係のライセンスが提供されます。同期関係を 20 個以上に設定し、 AWS から登録した場合は、追加の関係分を 1 時間単位で支払います。

https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS の年間価格を確認します"^]



== ネットアップのライセンス

同期関係のコストを事前に支払うもう 1 つの方法は、ネットアップからライセンスを直接購入することです。各ライセンスでは、最大 20 の同期関係を作成できます。

これらのライセンスは、 AWS または Azure サブスクリプションで使用できます。たとえば、 25 の同期関係がある場合は、ライセンスを使用して最初の 20 の同期関係に料金を支払い、残りの 5 つの同期関係を持つ AWS または Azure から従量課金制で支払うことができます。

link:task-licensing.html["ライセンスを購入して Cloud Sync に追加する方法について説明します。"]。



=== ライセンス条項

Cloud Sync サービスに Bring Your Own License （ BYOL ）を購入されたお客様は、ライセンス資格に関連する制限事項に注意する必要があります。

* お客様は、納品日から 1 年を超えない期間、 BYOL ライセンスを利用できます。
* お客様は、 BYOL ライセンスを利用して、ソースとターゲットの間の合計 20 個の個別接続を確立することができます（それぞれ「同期関係」）。
* お客様の利用資格は、お客様が 20 件の同期関係の制限に達したかどうかに関係なく、 1 年間のライセンス期間の終了時に期限切れとなります。
* お客様がライセンスの更新を選択した場合、以前のライセンス付与から関連付けられた未使用の同期関係は、ライセンスの更新には引き継がれません。

